services:

  auth-db:
    image: postgres:12
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123321
    ports:
      - 5432:5432

  product-db:
    image: postgres:12
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123321
    ports:
      - 5433:5432

  sales-db:
    image: mongo
    container_name: sales-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123321
    ports:
      - 27017:27017
      - 28017:28017
    
  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    hostname: sales_rabbit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672

  auth-api:
    build: './auth-api'
    container_name: auth-api
    depends_on: 
      - auth-db
    environment:
      - PORT=8080
      - API_SECRET=Y2hhdmVwYXJhYXBpc2NvbnRhaW5lcjEyMzMyMQ==
      - DB_HOST=auth-db
      - DB_NAME=auth-db
      - DB_USER=admin
      - DB_PASSWORD=123321
      - DB_PORT=5432
    ports:
      - 8080:8080

  product-api:
    build: './product-api'
    container_name: product-api
    depends_on: 
      - product-db
      - sales_rabbit
    environment:
      - PORT=8081
      - API_SECRET=Y2hhdmVwYXJhYXBpc2NvbnRhaW5lcjEyMzMyMQ==
      - DB_HOST=product-db
      - DB_NAME=product-db
      - DB_USER=admin
      - DB_PASSWORD=123321
      - DB_PORT=5433
      - RABBIT_MQ_HOST=sales_rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=8082
    ports:
      - 8081:8081

  sales-api:
    build: './sales-api'
    container_name: sales-api
    depends_on: 
      - sales-db
      - sales_rabbit
    environment:
      - PORT=8082
      - API_SECRET=Y2hhdmVwYXJhYXBpc2NvbnRhaW5lcjEyMzMyMQ==
      - MONGO_DB_URL=mongodb://sales-db:27017/sales-db
      - RABBIT_MQ_URL=amqp://sales_rabbit:5672
      - PRODUCT_API_URL=http://product-api:8081/api/product
    ports:
      - 8082:8082