server:
  port: ${PORT:8081}

spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:product-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123321}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBI_MQ_HOST:localhost}
    port: ${RABBI_MQ_PORT:5672}
    username: ${RABBI_MQ_USER:guest}
    password: ${RABBI_MQ_password:guest}

app-config:

  services:
    sales: http://${SALES_HOST:localhost}:${SALES_PORT:8082}

  secrets:
    api-secret: ${API_SECRET:uR1zYg8Z2/3kSbz6rds34SDsdh89jsdfgkjsdfslkdi==}

  rabbit:
    exchange:
      product: product.topic

    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue
