INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1000, 'Comic  Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Movies');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1000, 'DC comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY,FK_SUPPLIER,QUANTITY_AVAILABLE, CREATED_AT) VALUES (1000, 'Revista 1', 1000,1000,10, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY,FK_SUPPLIER,QUANTITY_AVAILABLE, CREATED_AT) VALUES (1001, 'Filme 1', 1002,1001,12, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY,FK_SUPPLIER,QUANTITY_AVAILABLE, CREATED_AT) VALUES (1002, 'Harry Potter', 1002,1001,3, CURRENT_TIMESTAMP);